### ISSUE TITLE
Add license to repositories

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#10]
- [x] Decide which license to use
- [x] store license in https://github.com/bonitasoft/bonita-documentation-site. Also update the `package.json` file. See #28
- [x] store license in https://github.com/bonitasoft/bonita-documentation-theme. Must be MPL-2.0 as this is derived from antora-ui. See https://github.com/bonitasoft/bonita-documentation-theme/commit/0f59de1590e99954a8c72b3a76ebc0b442defe7a

**Comment by benjaminParisel** [comment]
This is not mandatory for first iteration.

**Comment by benjaminParisel** [comment]
@nchabanoles Do you have some new informations about this issues ?

**Comment by tbouffard** [comment]
closing, for the license in the documentation content repositories, see #277
