### ISSUE TITLE
Re-write Bonita ICI menu & Bonita Continuous Delivery

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonita-documentation-site#123]
I think we should write "Bonita Intelligent Continuous Improvement (BICI)" and "Bonita Continuous Delivery (BCD)" in the menu
![image](https://user-images.githubusercontent.com/52718045/108793679-f2f9af00-7538-11eb-991e-171963d09426.png)

**Comment by alachambre** [comment]
The problem with this proposal is that it's way too long, it won't render nicely and will lead to issues depending of your screen size. It would be a pity (in my view) to ruin the UI for the only product that has been abandoned by the company. 
However we can make some tests and check how it renders and if we can think of something else.

**Comment by LBALP** [comment]
I agree, so what about > Bonita > Bonita Cloud > BCD > BICI ? (but we can't leave Bonita ICI..)

**Comment by benjaminParisel** [comment]
We will do it before migrate all mardown content to asciidoc

**Comment by tbouffard** [comment]
For bici, this entry doesn't exist anymore: it has been embed into the new labs menu
See #149

**Comment by tbouffard** [comment]
In addition, this menu is generated from the display name given to each component. This display name is used everywhere in the documentation site.
For instance, Bonita Continuous Delivery is used in component selection (at bottom right of each page), breadcrumb, ...
So this requirement is related to the documentation content.

**Comment by tbouffard** [comment]
Closing, let the Product Team decide. We currently have a request to rename `Bonita` into `Bonita Platform`
