### ISSUE TITLE
Migrate Markdown branch to ascidoc each night

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#151]
After our work on docSite and before to put alive this documentation site we don't want to block content contribution. 
We get a script to convert and manage some conversion issue. 

It will allow us to be sure conversion work fine.

- [ ] Create a github action to convert  each documentation content and push the result on ascidoc branch.

**Comment by tbouffard** [comment]
We are in the process of converting markdown into asciidoctor for good and, then, we won't need this afterwards.
So closing.
