### ISSUE TITLE
Investigate about linter for Asciidoc syntax

### ISSUE THREAD

**Issue by uguy** [bonitasoft/bonita-documentation-site#162]
Using a linter could be usefull for contributor in making `clean` pull request.

An issue exist on this topic: https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/6

They are mentioning a tool named vale that may be useful as a start. (see https://docs.errata.ai/vale/scoping#asciidoc)

**Comment by alachambre** [comment]
https://www.npmjs.com/package/textlint-plugin-asciidoctor

didn't test

**Comment by jeromecambon** [comment]
I tested Vale, which is NOT an Asciidoc syntax linter, but a check on the syntax style.
One may define a set of rules to check, with different severities. A set of pre-defined set of rules can be used : Google, proselint, write-good, ...
An example using this rules, on the Bonita page "Data Management in the UI Designer":
![Screen Shot 2022-09-02 at 2 42 01 PM](https://user-images.githubusercontent.com/17833345/188147599-32207b34-a551-4775-885a-148a465c2ff8.png)

**Comment by jeromecambon** [comment]
I also tried [textlint-plugin-asciidoctor](https://www.npmjs.com/package/textlint-plugin-asciidoctor), but didn't succeed to make it work.
Anyway seems a very limited package, with very few support.

**Comment by jeromecambon** [comment]
The Vale github action provides a smart reporter in the "Check" PR section, as well as in the "Files changed":

https://user-images.githubusercontent.com/17833345/195867268-50570f96-b5ee-4787-a598-215b9f26b99d.mov
