### ISSUE TITLE
Push html for archived documentation somewhere

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#166]
For now, our bundle is not stored anywhere. If we want the bundle, we need to run github workflow.

Our proposal is to create a release for each archived branch and upload it manually.

We want to do it after the first review on a new content branch by bonitastofter

**Comment by benjaminParisel** [comment]
Example: I have manually [released ](https://github.com/bonitasoft/bonita-doc/releases/tag/7.3_archived)from 7.3_asciidoctor branch and upload artefact generated by on [GitHub workflow ](https://github.com/bonitasoft/bonitasoft.github.io/actions/workflows/generate-static-doc.yml)as release attachment

**Comment by benjaminParisel** [comment]
We're all agree to store our archive documentation bundle as github release attachment .
To do it we need to: 

- [ ] Create a github Release on dedicated branch and join bundle
- [ ] Update or create procedure in release process to publish new archived documentation bundle

**Comment by tbouffard** [comment]
All additional tasks have been managed, so closing.
