### ISSUE TITLE
Switching the theme when content is looong takes time - some simple loader can be good to improve UX

### ISSUE THREAD

**Issue by aibcmars** [bonitasoft/bonita-documentation-site#211]
**What**
[As seen in the preview below]
I searched for the 'diagram API' => the page is really looong and when I switch the theme it takes time, it looks frozen

**Proposed solution**
If you can add a loader (any simple notification that action is in progress) it will improve the experience.

```
Windows
Google Chrome is up to date
Version 89.0.4389.82 (Official Build) (64-bit)
```

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/45601541/110918618-a6c1b380-831b-11eb-9990-7848ba74adc4.gif)

**Comment by alachambre** [comment]
Hey Marcin! 

I noticed this too, I would love to have your help on this topic, I tried some stuff to improve the perfs but my poor web dev skills failed me once again!

**Comment by tbouffard** [comment]
Closing thanks to https://github.com/bonitasoft/bonita-documentation-theme/pull/51 integrated with #221
