### ISSUE TITLE
Highlight pages related to out of support versions

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#22]
**Goal**: explicitly inform users that they are using out-of-support versions and provide a link to the newest version

### Old site design

In the old documentation, this was sometimes done by changing the "Fork me on " rubber into "Out of support". On `2020-11-19`, this was only available in the `Bonita 7.3` documentation
Using the rubber is not the best choice as we use the same design for 2 different things and users associate the rubber to a link for contributions, so don't pay attention to the "out of support" text.

![out of support](https://user-images.githubusercontent.com/27200110/99647981-ca9e7800-2a52-11eb-929a-9c9b06ce6f6b.png)

![fork me on github](https://user-images.githubusercontent.com/27200110/99648081-ebff6400-2a52-11eb-8a85-baee6b08277a.png)

#### Add a specific banner in pages

Let's have a look to the solution provided by the [Couchbase Antora UI project](https://github.com/couchbase/docs-ui/blob/v269/README.adoc#view-latest-and-canonical-url): a banner is added to the top of the page and provide a link to the latest available version.
We could use the same logic to have a banner with a warning. A out of support version could be configured in the doc content repository antora configuration file at branch/version level (as an asciidoctor attribute or any other available configuration)

![couchbase](https://user-images.githubusercontent.com/27200110/99648524-6c25c980-2a53-11eb-9746-d2bc17dfb7e2.png)

### Displayed version

In addition, we could update the display version like proposed in https://docs.antora.org/antora/2.3/component-display-version/#display-version-key: `7.7 EOL`
See also #33

**Comment by NathalieC** [comment]
Whatever the version supported, a user will search for the version of Bonita they use, and I guess they know it's an out-of-support version.
So if we decide that the best way is to navigate them to a more recent version, then we need to let them know what is different between their Bonita version, and the version of the doc we navigate them to.

**Comment by tbouffard** [comment]
The concept of out of support Bonita versions is something that have been unclear for a long time. AFAIK, there is nothing available publicly about the out-of-support policy especially for the Community edition. If some new links have been added recently, please let me know, but for sure, this has been added recently for 2021.1
Making it explicit in the documentation and putting a link to the release cycle and out-of-support policy will be a great gain for everybody.
And out of support version also means no documentation update as well.
