### ISSUE TITLE
Reduce pictures size in documentation content

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#220]
Some or all images have so strong size. It will consume more bandwidth.
We need to find how we can optimize these pictures.

Netlify also provides assets optimization, see https://docs.netlify.com/site-deploys/post-processing/
This will be a way to reduce bandwidth consumption and reduce load time for the documentation readers.

### Information about the size of the assets
Note: #403 will help getting the generated site size by checking the logs of the GH workflow run

Whole doc site built on 2021-11-09
all components
```
9,2M    ./_
3,0M    ./cloud
606M    ./bonita
2,9M    ./bcd     → 3.4 and 3.5
704K    ./labs
622M    .
```

bonita
```
24K    ./0          --> archives
26M    ./7.6
27M    ./7.7
27M    ./7.8
78M    ./7.9
87M    ./7.10
90M    ./7.11
95M    ./2021.1
89M    ./2021.2
89M    ./1          --> 2022.1
606M    .
```
older versions were smaller
- [7.3](https://github.com/bonitasoft/bonita-doc/releases/tag/7.3-20210311_130652): 23.7MB (unzipped)
- ....

Details for Bonita 2021.2 on 2021-11-16, a very large amount of space is used in the `getting-started` module (tutorial)
module `getting-started` images: 65 elements for 61,2 MB
Lot of gif, with several from 1 to 2 MB

```
600K    ./api
1,1M    ./applications
297K    ./best-practices
369K    ./bonita-overview
1,1M    ./data
59M    ./getting-started
792K    ./identity
13K    ./integration
1,4M    ./pages-and-forms
1,4M    ./process
2,3M    ./ROOT
2,5M    ./runtime
21K    ./security
73K    ./setup-dev-environment
41K    ./software-extensibility
157K    ./version-update
71M    .
```

**Comment by jeromecambon** [comment]
While compressing a single png is quite long (1m30s for the example above), it is OK on a set of png (2m30s for 29 png)

**Comment by jeromecambon** [comment]
For animated gif (used a lot in the tutorial, with very big files): 
https://github.com/kohler/gifsicle (not tested yet)

**Comment by jeromecambon** [comment]
Animated GIFs from the Getting Started tutorial have been compressed in all versions (from 7.9, no animated GIFs before), using the online tool https://www.iloveimg.com/compress-image.

**Next step**: 
add a warning if an image is > 1 Mo (for instance) in "Contribution check" action, and point on the tool above.

**Comment by tbouffard** [comment]
Size of the generated site from https://github.com/bonitasoft/bonita-documentation-site/actions/runs/3065290246/jobs/4949255867 run on Fri, 16 Sep 2022 03:58:26 GMT

```
1.3M	./bcd/3.6
1.7M	./bcd/3.4
1.3M	./bcd/3.5
4.2M	./bcd
716K	./labs/latest
720K	./labs
512K	./test-toolkit/1.0
516K	./test-toolkit
1.3M	./_/js
160K	./_/stylesheets
192K	./_/img
7.4M	./_/font
9.0M	./_
3.3M	./cloud/latest
3.3M	./cloud
27M	./bonita/7.8
24K	./bonita/0
75M	./bonita/2021.1
67M	./bonita/7.10
27M	./bonita/7.7
70M	./bonita/2021.2
69M	./bonita/7.11
58M	./bonita/7.9
70M	./bonita/2022.1
70M	./bonita/2023.1
70M	./bonita/2022.2
600M	./bonita
618M	.
```

**Comment by jeromecambon** [comment]
- [ ] Reduce size of animated gif files
- [ ] Reduce size of the images

**Comment by jeromecambon** [comment]
Using [optopng tool](https://www.tecmint.com/optimize-and-compress-jpeg-or-png-batch-images-linux-commandline/), we reduce by ~38% the total size of all the png files:
```
$ find . -name "*.png" -type f -exec du -ch {} + | grep total$
 12M	total
$ find . -name "*.png" -type f -exec optipng {} +
$ find . -name "*.png" -type f -exec du -ch {} + | grep total$
8.7M	total
```

**Comment by tbouffard** [comment]
> Using [optipng tool](https://www.tecmint.com/optimize-and-compress-jpeg-or-png-batch-images-linux-commandline/), we reduce by ~38% the total size of all the png files:

for all components and branches, or some bonita branches? Remember that you can find the size of the generated site in the logs of the github actions for both preview and production.

**Comment by jeromecambon** [comment]
> > Using [optipng tool](https://www.tecmint.com/optimize-and-compress-jpeg-or-png-batch-images-linux-commandline/), we reduce by ~38% the total size of all the png files:
> 
> for all components and branches, or some bonita branches? Remember that you can find the size of the generated site in the logs of the github actions for both preview and production. See [#220 (comment)](https://github.com/bonitasoft/bonita-documentation-site/issues/220#issuecomment-1249013109) for instance

I ran this on the 2022.2 branch

**Comment by tbouffard** [comment]
> I ran this on the bonita-doc 2022.2 branch

Why didn't you run it in the oldest branch? do you plan to do it or only in 2022.2 then 2023.1?

**Comment by jeromecambon** [comment]
> > I ran this on the bonita-doc 2022.2 branch
> 
> Why didn't you run it in the oldest branch? do you plan to do it or only in 2022.2 then 2023.1?

I don't think it deserve to do it on older versions, since it only save ~3Mb. It was different with animated GIFs, where we saved 10th of Mb. 
Should be reflected in 2023.1 branch, right?

**Comment by tbouffard** [comment]
OK, the risk of not doing it on older branches is that it will generated merge conflicts when an image is modified in the old branch. As the work is already done in 2022.2 and images are rarely updated, let's keep it like it is now, but please keep this in mind for the next time you work on the documentation content or resources of a given version.

For 2023.1, most of the job will be done when the merge of 2022.2 into 2023.1 will be done. Only images added in 2023.1 will require a manual size reduce.
