### ISSUE TITLE
Source code rendering: display a button to copy the source code

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#226]
This is available in the Asciidoc documentation, for instance in https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/

![asciidoc_source_code_copy_button](https://user-images.githubusercontent.com/27200110/114502630-62804680-9c2c-11eb-8b18-fd7d743e1659.gif)

_(also available in the [Antora documentation](https://docs.antora.org/antora/2.3/install-and-run-quickstart/#create-a-playbook))_

We should check if there is some discrepancies between our theme and the Antora Default UI to understand why we don't have this feature.
- if this is available in the latest Antora Default UI
- if this has been disable in our documentation theme

 See also #227

**Comment by alachambre** [comment]
Here is the commit we want to cherry pick: https://gitlab.com/antora/antora-ui-default/-/commit/1a66a0d7ae045716290efc957cf8177f07bd9d52

**Comment by tbouffard** [comment]
Yes thanks!
I am on it, there are also fix commits that been pushed after the initial one
