### ISSUE TITLE
Decide how to manage documentation-theme update with new Antora Default UI  features

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#227]
The documentation theme has been created from the [Antora Default UI](https://gitlab.com/antora/antora-ui-default), but
- we currently don't have documented (and may not know) the commit used as starting point for our theme
- we have never applied changes (improvements, fixes) from Antora Default UI to our theme

We need to clarify how we can benefits from improvements and fixes, in particular if a new version is required when migrating to Antora 3.0+.
Also remember even we have tried to limit the number of internal structure changes, we have migrated css to scss that could lead to more work when trying to reintegrate Antora Default UI changes.

See also #226 

[UPDATE 2021-10-19] Antora dev are thinking about changing the way the UI integration will be done in the future, see 
https://gitlab.com/antora/antora.org/-/issues/20#note_707337777

**Comment by alachambre** [comment]
On my personal repository (the initial fork of the default UI), the [first commit](https://github.com/alachambre/antora-ui/commit/14b307b014f6b68da28d71e4357568a8ce760b10) has been done the 08/10/2020 , which correspond to [this commit](https://gitlab.com/antora/antora-ui-default/-/commit/4f54fb8f47a51bdb37140f176ddbe1a6a5ecb1c1) of the default ui.

On the documentation-theme repository, the [first commit](https://github.com/bonitasoft/bonita-documentation-theme/commit/0f59de1590e99954a8c72b3a76ebc0b442defe7a) has been done the 12/11/2020, but I do not remember if I forked again the base repository or if I started from my personal repository.


According to what I'vs been able to read, the recommended strategy is to cherry pick the commit we are interested by, it seems too complicated to maintain a sync between the base repo and the fork. 
This has never been done (but it should have, i'm sry /=) so it's gonna be painful if we decide to do it today.

**Comment by tbouffard** [comment]
Thanks @alachambre for the information.
I guess we need at least to cherry-pick some parts. For instance, if we want to benefits from #226

**Comment by tbouffard** [comment]
I have just push the master branch of the original gitlab repository in bonita-documentation-theme `antora-ui-default`.
This will help following diff, update and manage cherry-picks.

![image](https://user-images.githubusercontent.com/27200110/151346321-5fd879db-a053-4c39-940e-61494a5feee7.png)

**Comment by benjaminParisel** [comment]
We decide to explain the way to update antora-ui-default in this [commit](https://github.com/bonitasoft/bonita-documentation-theme/pull/71/files)
