### ISSUE TITLE
Investigate the Antora 3.0 upgrade and new features

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#229]
For Antora UI, see #227 
For other maintenance questions, see also #231 

Antora 3.0 is **available** (https://docs.antora.org/antora/3.0/whats-new/)
- GA released on `2021.12.25` aka christmas gift
- rc-2 released on `2021.12.07`
- beta-4 released on `2021.11.30`
- beta-3 released on `2021.11.24`
- beta-2 released on `2021.11.16`
- beta-1 released on `2021.11.03`
- alpha-10 released on `2021.10.22`
- alpha-2 released on `2021.04.08`
- alpha-1 released on `2020.09.29`

We can already check if we use remove features/settings and what we can benefit from an upgrade.

### Features that will help us
**NOTE**: non exhaustive list, investigations in progress

Better logging system and xref issues detection ✔️  #266
- log infrastructure, log level and log failure level: https://gitlab.com/antora/antora/-/issues/145
- logs files that have xref resolution issue: https://gitlab.com/antora/antora/-/issues/403
- even possible to have the line number: https://docs.antora.org/antora/3.0/playbook/asciidoc-sourcemap/

Attachments referenced with the AsciiDoc xref macro and their Antora resource IDs
- https://docs.antora.org/antora/3.0/whats-new/#attachment-resource-ids
- avoid the link syntax and simplify cross component, version and modules attachments sharing
- same syntax as for images, partials

Latest version URL customizations 🚧  (redirects and version list #266, to test impacts on Algolia search)
- since 3.0.0-alpha-1
- https://docs.antora.org/antora/3.0/whats-new/#latest-version-url-customizations
- https://docs.antora.org/antora/3.0/playbook/configure-urls/
- less configuration for promoting GA version (mainly bonita and bcd)
- Strategy: generate redirects with http 302 for webserver, see https://docs.antora.org/antora/3.0/playbook/urls-latest-version-segment-strategy/
- detailled example
  - latest release named 'stable' in url: https://docs.antora.org/antora/3.0/playbook/urls-latest-version-segment/
  - latest pre-relese named 'next' in url: https://docs.antora.org/antora/3.0/playbook/urls-latest-prerelease-version-segment/#specify-a-latest-prerelease-version-segment

Others - repo content management
-  https://docs.antora.org/antora/3.0/playbook/content-worktrees/: usefull for author mode. When working locally on several branches of the same repo via git worktree, Antora can use the worktree content (no need for commit and push), faster feedback loop
- Symlinks and also for windows - when defined it in the git repo
- root component (beta 2): https://docs.antora.org/antora/3.0/whats-new/#root-component 
- component with both version and undefined version: can be used as a home for a component, introducing the component and provide shared information

Others - Antora
- generator in playbook (beta 2): https://docs.antora.org/antora/3.0/whats-new/#generator-in-playbook
 - [Antora extensions](https://docs.antora.org/antora/3.0/extend/extensions/): a clean way to hook with Antora lifecycle. Reduce the need for model customization in the Antora UI ✔️  #266 (used to change the alpha version position in the version list - mandatory for us)
    
Others - Asciidoctor 2 support
- collapsible block, in particular example block: https://docs.asciidoctor.org/asciidoc/latest/blocks/collapsible/#collapsible-block-syntax
- see the upgrade notes: https://docs.antora.org/antora/latest/asciidoctor-upgrade-notes/ If we use standard Asciidoc syntax, we should not see much changes.

**Comment by alachambre** [comment]
About the support of Asciidoctor 2, I suggest to be careful with the update on tables a & l column modifier (https://docs.antora.org/antora/latest/asciidoctor-upgrade-notes/#tables)

I do not really understand what's the update, but I know we do use those modifiers here and there is the documentation.

**Comment by tbouffard** [comment]
Investigation have been completed for a while, we have been using Antora 3 since March 2022, and recently bump to Antora 3.1 #414. So closing.
