### ISSUE TITLE
Document targeted Architecture

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#25]
A global schema should be nice

To be reviewed with final decision
- search: Algolia + indexation
- deployment/hosting: ~GH pages~ Netlify
- doc source: 1 gh repo per component + branches
- site generation: site repo with Antora
- build automation: gh actions
- preview

**Comment by benjaminParisel** [comment]
A bigPicture schema is start [here](https://docs.google.com/drawings/d/1eVQPXv9F0xMh7bkuP1ecuGoiwYM73f9mDl0VCs2BVXc/edit)

**Comment by tbouffard** [comment]
A dedicated page has been created and the schema is displayed on it.
So closing this issue, feel free to improve
