### ISSUE TITLE
Theme: make the 'next version' and 'out of support' banner always visible

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#274]
Currently, the banner is only visible when we are at the top of the page, if we scroll or land to the page directly to an anchor, we don't see it.

### Current L&F

eol version | next version
--------- | ----------------
![bonita_eol_version](https://user-images.githubusercontent.com/27200110/145086074-0ea6e0ce-ced1-4722-9241-ae2e3447959f.gif) | ![bonita_next_version](https://user-images.githubusercontent.com/27200110/145086080-ede04cc9-368a-44b1-bc75-86ba631327f4.gif)

### Proposition

Make is always visible as in the corteza documentation. Notice they have a real nice look and feel, including the font.

See https://docs.cortezaproject.org/corteza-docs/2020.9/index.html and https://docs.cortezaproject.org/corteza-docs/2021.9-develop/index.html (update the link if this version is no more available as it has been released)
Done with https://github.com/cortezaproject/corteza-docs/blob/4bb9244ed37b71aa81c15c1ad27821da7b1d062c/antora/ui/partials/toolbar.hbs

eol version | dev version
--------- | ----------------
![warn_eol_version_always_visible](https://user-images.githubusercontent.com/27200110/145085234-2f565fd6-b7ec-4381-9b6d-9ab78ce29c2a.gif) | ![warn_next_version_always_visible](https://user-images.githubusercontent.com/27200110/145085229-5e74ce6c-6e1c-4822-af2f-af537572d002.gif)

**Comment by benjaminParisel** [comment]
See witch @NathalieC. Go for it !
