### ISSUE TITLE
Update the troubleshooting sections in the contributing guide and in the documentation content

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#334]
Until recently, the troubleshooting section should be written by following the Contributing guide.
https://github.com/bonitasoft/bonita-documentation-theme/pull/85 provides a AsciiDoc semantic way that Doc Writer should follow instead.

- [x] update the contributing guide. Link to the theme content, and live preview if/when available #335
- documentation content. The following was the initial proposal. It won't be done by the doc-site project team, see https://github.com/bonitasoft/bonita-documentation-site/issues/334#issuecomment-1220369448
  - check repositories providing troubleshooting sections (following the past recommendations or not) **(to be listed here)**
    -  bonita starting from version ??
  - determine the documentation versions that need to be migrated  **(to be listed here)**
    - from Bonita 2021.1(7.11 is out of support in June 2022)
  - migrate the sections. @NathalieC (see https://github.com/bonitasoft/bonita-documentation-site/issues/334#issuecomment-1156140007)
  - remove the troubleshooting images stored in the content repositories

**Comment by benjaminParisel** [comment]
@NathalieC will doing the "migration" and check with Support team if they have the information about the new format.

**Comment by benjaminParisel** [comment]
We decide to give a new way of writing the troubleshooting section to the Support team! We will plan a session to update one old troubleshooting with us.

**Comment by benjaminParisel** [comment]
I open a [PR](https://github.com/bonitasoft/bonita-doc/pull/2178) to move the oldest way or writing to the new syntax. We can reference this PR when we would like to share an example with our writers.

**Comment by tbouffard** [comment]
The PR was merged so closing the issue.

**Comment by tbouffard** [comment]
The PR was merged so closing the issue.
