### ISSUE TITLE
Check if we can use font awesome icons or other icons set

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#36]
### Status with the old documentation site

In the old documentation site, it was possible to use font awesome icons.

For instance the BICI index page uses icon with links to release-notes, getting started, ... (https://github.com/bonitasoft/bonita-ici-doc/blob/1bfba7e81f38250e568a5b1a4f29b4b6125f6215/md/index.md)

![image](https://user-images.githubusercontent.com/27200110/100003968-1b053500-2dc7-11eb-9d6c-a273a638ee82.png)

Same for BCD (https://github.com/bonitasoft/bonita-continuous-delivery-doc/blob/0538a65330f0058f5b3c5f36c3199c0e42529b03/md/index.md)

![image](https://user-images.githubusercontent.com/27200110/100002338-b943cb80-2dc4-11eb-8311-f83564bc8269.png)

Same for Bonita Cloud (https://github.com/bonitasoft/bonita-cloud-doc/blob/cf6c2e6d478b40a5ce688d6f76a4b945a7241b82/md/index.md)

![image](https://user-images.githubusercontent.com/27200110/100002992-b3021f00-2dc5-11eb-8411-ea360b147ef6.png)

### To be investigated
Providing icons support helps the documentation to be more attrative, so we should check what we can provide on this side.
This is possible with Asciidoctor (https://asciidoctor.org/docs/user-manual/#icons). See what is possible with Antora.

This may be related to #66

[UPDATE 2022-01-10] https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20font.20awesome. It should work as in a regular AsciiDoc page: declare the icon set as AsciiDoc attribute and use the icon macro: https://docs.asciidoctor.org/asciidoc/latest/macros/icons/

**Comment by benjaminParisel** [comment]
After using the doc-site than more one year, we don't hany request about this subject. That's why we decide to close this issue.

**Comment by uguy** [comment]
Reopened to work on icon support :smiley:

**Comment by tbouffard** [comment]
https://github.com/bonitasoft/bonita-documentation-theme/pull/184 has been merged and is part of https://github.com/bonitasoft/bonita-documentation-theme/releases/tag/v1.12.0
This version of the theme is now used to build the site: #556 (#554 was not merged because of an issue in the 1.12.0 theme)
