### ISSUE TITLE
Theme: improve rendering of the pagination links

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#362]
We currently use the pagination look and feel provided out of the box by the Antora Default UI. See #273 

I suggest we introduce pagination elements using something similar to the following example

- boxed
- highlight/shadowed on hover like we do for cards

Docusaurus like in https://playwright.dev/docs/test-auth

![playwright_pagination_links](https://user-images.githubusercontent.com/27200110/168957014-917894cf-0f8c-4c10-8b27-72906b99146b.gif)

https://boozallen.github.io/sdp-docs/deployment-guides/1/openshift/index.html using Antora custom UI

![boozalen_pagination_links](https://user-images.githubusercontent.com/27200110/168956796-31c2aa2f-c1d4-40cc-bf9e-1e95b6183cca.gif)

**Comment by benjaminParisel** [comment]
First screenshot from Docusaurus is better than the second

**Comment by benjaminParisel** [comment]
I have tried a first display and I got this render. Current branch is [here]([theme/improve_navigration_displaying](https://github.com/bonitasoft/bonita-documentation-theme/tree/theme/improve_navigration_displaying)

![image](https://user-images.githubusercontent.com/25297128/182185173-af93a2c1-63d0-497a-bbe9-d2bfd541ed4c.png)

![image](https://user-images.githubusercontent.com/25297128/182185248-3a140ec1-b2b8-45fb-b5c9-f17332f3ba59.png)

**Comment by tbouffard** [comment]
https://github.com/bonitasoft/bonita-documentation-theme/pull/115 available in theme v1.5.0 which is now in production. See #409
So, closing.
