### ISSUE TITLE
Simplify doc content reviewer life: provide preview urls links in PR

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#373]
Today, we a PR is created, reviewers have no way to easily get links to the pages changed by the PR.
They have to retrieve the list of the modified source AsciiDoc pages and then build the urls manually.

We would like to propose that the list of urls is shown as a PR comment. We could use https://github.com/marocchino/sticky-pull-request-comment (or https://github.com/marketplace/actions/create-or-update-comment, or similar action) to create the PR comment and to have a single comment that is updated on PR update

**Comment by benjaminParisel** [comment]
In the first iteration of action add a comment like this on the PR

![image](https://user-images.githubusercontent.com/25297128/199931062-5cac46ac-5634-434a-96d2-a0a4c5705291.png)

In addition, we want to add a warning message when some .adoc file is renamed or deleted to prevent users to add an alias for these deleted/renamed files.

To do it, we use this https://github.com/tj-actions/changed-files action
