### ISSUE TITLE
Integrate the new Bonita REST API documentation

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#39]
https://github.com/bonitasoft/bonita-openapi provides an OpenAPI file that can be used to generate the REST API documentation.
We would like to remove the manually maintained REST API documentation from the Bonita documentation and replace it by a new documentation section generated from the OpenAPI resources.

To be discussed
- how do we integrate the new documentation based on OpenAPI? pre-generated content in asciidoctor produced from the OpenAPI spec then registered as an Antora component? produced html by the OpenAPI tooling?
- how do we migrate from the old documentation to the new documentation? mark the old documentation as deprecated and link to the new one? remove the old doc in supported Bonita version

**Comment by alachambre** [comment]
Other questions: 
- Does the API documentation have to be SEO compliant (i.e static HTML)?
- Do we want to be able to search on the API documentation using the global search ? 

Each 'yes' means more work to do :D

**Comment by benjaminParisel** [comment]
We will close this issue. If the needs become back on product roadmap, we can reopen it again.
