### ISSUE TITLE
Content Repositories: limit the effects of xref validation errors due to changes in other repositories

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#399]
As described in  #326, we currently enforce xref validation in documentation content PR. This requires that more and more component versions being built a
Contributors see failures due to changes in other repositories (see https://github.com/bonitasoft/bonita-documentation-site/issues/326#issuecomment-1164120720) and this is frustrating: they have to dig into the GH Actions logs (some have limited technical backgrounds, so log are cryptic for them), and then, have to add the new component version in the preview GH workflow definition to fix the error.

This mainly appends in bonita-doc and bcd repositories.

### Proposal

Disable xref validation when deploying the preview: the comment in the PR will be created even if there are xref validation error. This lets contributors see changes in the preview.

Have a dedicate checks for build site errors: the contributor will better see that the issue probably comes from a xref validation error

### Macro tasks

preview script: have an option to disable failure on error. Name to be found

For build site error detection, if possible, do not generate the content to speedup the build. This was previously possible prior Antora 3 with a dedicated Antora site-generator

implementation
- build the site preview with only the component version of the PR
- then build the site preview with all component versions to make the xref validation pass

Possible solutions
- solution 1: run the 2 previews sequentially in the same job
  - cons: no distinct errors for the xref validation and deployment errors
- solution 2: 2 distinct jobs
  - pros: distinct errors, can run in parallel (so potentially, faster feedback)
  - cons: configuration duplication? more usage of GH runners

To review
  - We may introduce an action that can hide the call to the preview script for the site preview deploy: pass only the name of the component, the name of the branch can be deduced from the PR
  - have an action that can manage both use case? with an option to disable or not the "fail on error"

**Comment by benjaminParisel** [comment]
I prefer solution 2, to distinct more easier the potentially error
