### ISSUE TITLE
Make Antora manage latest and next version alias

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#419]
Having this will simplify developer workflow when new versions are added or released: no Netlify redirect to manage.
We will have canonical urls to latest for all components, so we could easily configure the robots.txt to only index the latest version of each component in Google and other search engines.

Latest version URL customization 
- since 3.0.0-alpha-1
- https://docs.antora.org/antora/3.0/whats-new/#latest-version-url-customizations
- https://docs.antora.org/antora/3.0/playbook/configure-urls/
- less configuration for promoting GA version (mainly bonita and bcd)
- Strategy: generate redirects with http 302 for webserver, see https://docs.antora.org/antora/3.0/playbook/urls-latest-version-segment-strategy/
- detailled example
  - latest release named 'stable' in url: https://docs.antora.org/antora/3.0/playbook/urls-latest-version-segment/
  - latest pre-relese named 'next' in url: https://docs.antora.org/antora/3.0/playbook/urls-latest-prerelease-version-segment/#specify-a-latest-prerelease-version-segment

### Notes

**Info:** basic investigations were done in #266

### Impacts on the Algolia Search 

This will have impacts on the Algolia search: url will be indexed with latest and next key, and not with the actual component version.
Without any changes on the site and theme, here is what would happen
- after the switch to production and before reindexation, search works as before
- after reindexation, DocSearch uses latest, site use actual version, so the search always returns no match

So, we need to change the query sent to DocSearch on the site/theme side.

In Antora 3.1, the virtual latest/next version values may be available in the Antora model, so the Theme templates could pass the new properties instead of the version value to DocSearch. See https://docs.antora.org/antora/3.1/whats-new/
However, once the new site is in production, until we reindex, site would use latest but the index only has the actual version. So, search would return no match.
We will also have no results while developing the new theme.

To mitigate this, we could change the versions in the DocSearch query.
For the latest version of the component, we could pass both latest and the actual version. That way, we won't have to worry about the URL switch. 

See also https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20Get.20latest.20version.20segment.20in.20template/near/295031102

### Impacts on PR Comment created to list modified page to check in the preview

The comment lists the preview URL related to the documentation pages that changed.
It uses the actual version, not latest or next to build the URL. In a preview, there is only a single version of the component, so the version is latest or next (if it is defined as a pre-release).
We need to ensure that in that case, a redirect is available in the preview. Otherwise, listed URLs would lead to HTTP 404.

### Possible implementations

Discussed with @jeromecambon and @tbouffard on `2023-03-03`

#### General solution

We need to implement an Antora extension (https://docs.antora.org/antora/3.1/extend/extensions/) to pass to the DocSearch client both the actual version and the latest/next version.
The information about the second version will be computed in the extension and stored in the Antora model or in an AsciiDoc attribute. Then, this information will be used by the documentation theme during page generation.

#### Option 1 - create AsciiDoc attributes about page is latest or next

Antora states is already create a page attribute  to know if the page relates to a latest version: `page-component-version-is-latest`. See https://docs.antora.org/antora/latest/page/intrinsic-attributes/#page-attributes
We would create a new attribute when we detect it is the next version.

In the documentation theme, if the attribute for latest or next version is set, we pass the corresponding extra version (latest or next) to the DocSearch client in addition to the regular version.
The values will be hard coded in the theme but they won't change (otherwise we would have to setup redirection). We develop a specific theme, we are not trying to create a general purpose theme, so we don't need it to be generic and ready for reuse.

#### Option 2 - store the "alias version"

Set in the model or AsciiDoc attribute the "alias version" which relates to the version segment in the Antora configuration.
The value is set if we detect that the version is latest or next
In the documentation theme, if we found the alias version, we pass it to the DocSearch client in addition to the regular version.

It is possible to not hard code the latest/next value, but retrieve the version segment from the Antora playbook.
It is possible to store this value in AsciiDoc page attribute: see https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20Get.20latest.20version.20segment.20in.20template

This will avoid to hard code anything in the extension and in the documentation theme.

### Chosen implementation option

The extension computed a version alias when it is needed
- the version is detected as latest or next
- the version is not already "latest" (avoid passing the version twice to the DocSeach Client)

The value of the alias is taken from the Antora configuration file (inspired from the sugestion provided in the Zulip chat).
The extension create a new AsciiDoc page attribute that stored the alias version.

When available, the documentation-theme use the "alias version" attribute to add a new parameter used by the DocSearch client.

**Comment by jeromecambon** [comment]
I've checked that the redirect works well in the preview, by running surge locally on my generated site (with `latest` and `next`)

**Comment by tbouffard** [comment]
> I've checked that the redirect works well in the preview, by running surge locally on my generated site (with `latest` and `next`)
@jeromecambon I guess you are talking about the netlify redirects generated by Antora that you test locally with the netlify dev server.
