### ISSUE TITLE
Doc content repo: set GH_TOKEN default permissions to read

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#443]
Resources
- https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
- https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

It is possible since we have set permissions in GitHub workflows as part of #270

![image](https://user-images.githubusercontent.com/27200110/193737391-1694d6ce-aebf-4a0c-86ae-b60fdcb57f21.png)

- [x] bcd (2022-10-04). Requires #418
- [x] bonita-doc. Needs to set permissions for 
  - [x] pr-title checks: https://github.com/bonitasoft/bonita-doc/pull/2185
  - [x] close stale PR: https://github.com/bonitasoft/bonita-doc/pull/2184
- [x] cloud (2022-10-07). Also disable dependabot alerts and increase artifact and logs retention from 5 to 15 days
- [x] labs (2022-10-07)
- [x] test-toolkit.
  - [x] Need to set permissions for close stale PR: https://github.com/bonitasoft/bonita-test-toolkit-doc/pull/27

**Comment by benjaminParisel** [comment]
All tasks are done, I close this issue, nice job! :handshake:
