### ISSUE TITLE
CI: From github action, add label when PR are opened

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#456]
When user open a PR in the documentation, they can't add label "Review needed" or add some reviewer.

It's a normal use-case because they are not a collaborator on this repository.

To by-pass this issue. I suggest adding the **"review needed"** label when PR is opened. We can do it by adding an action.

![image](https://user-images.githubusercontent.com/25297128/197561893-dc7f29cc-1204-4ee4-a5c8-daa6f0d5369f.png)

**Comment by tbouffard** [comment]
I suggest that when the PR is opened in Draft a WIP label is put instead.
The same should be done when switching from In Review to Draft and the opposite

**Comment by benjaminParisel** [comment]
After some research, we didn't find an action to manage all user flow mentioned in previous comments.

<table>
	<tr>
	 <td>PR is opened as a Draft, a WIP label is put instead.
	 <td> :no_entry_sign: 
	 <td> when A PR opened as a Draft, is obvious a WIP contribution, so we didn't label.
 	<tr>
	  <td>PR status change from draft/in-review
	  <td> :heavy_check_mark: 
 	  <td> put only the **in review** label if there is no **review done** or **ready to merge** label already set	 
  <tr>
	  <td>PR is mark as approved/rejected
	  <td> :heavy_check_mark: 
	  <td> Adding a Label **review done** instead of **in review** and **ready to merge** or **changes requested**
</table>

As much as we can, prepare a common job to allow re-usable flow in other documentation content.
