### ISSUE TITLE
The Vale syntax checker should not set the PR in error

### ISSUE THREAD

**Issue by jeromecambon** [bonitasoft/bonita-documentation-site#464]
Currently, the Vale syntax checker we have enabled on the bonita-doc repository set the PR in error as soon as a Vale warning appears. 
See [this PR](https://github.com/bonitasoft/bonita-doc/pull/2213) for instance.

**Comment by jeromecambon** [comment]
This is related to [an issue in the Vale action](https://github.com/errata-ai/vale-action/issues/84) that makes the workflow to fail.
This is also not possible to set the reviewdog 'level' parameter, that would allow to set the error level.

**Comment by tbouffard** [comment]
> Moreover, it seems it is not possible to force a workflow to have an exit code different of 'failure' (see [docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions))

This link is about setting an action exit code, not the workflow exit code. What we would like is to set the workflow global status to neutral or something similar. This may not possible for now as well.

**Comment by tbouffard** [comment]
ℹ️ Vale is disable in bonita-doc until we found a solution: https://github.com/bonitasoft/bonita-doc/pull/2218

**Comment by jeromecambon** [comment]
Still an issue that make reviewdo to fail, when we have big files with many errors/warnings:
```
Error: reviewdog: Too many results (annotations) in diff.
  You may miss some annotations due to GitHub limitation for annotation created by logging command.
  Please check GitHub Actions log console to see all results.
  
  Limitation:
  - 10 warning annotations and 10 error annotations per step
  - 50 annotations per job (sum of annotations from all the steps)
  - 50 annotations per run (separate from the job annotations, these annotations aren't created by users)
```

**Comment by jeromecambon** [comment]
Created an issue for Vale about this:
https://github.com/errata-ai/vale-action/issues/89

**Comment by jeromecambon** [comment]
I made a fix and wanted to create a PR, but don't have (yet) the rights to do it.

**Comment by tbouffard** [comment]
@jeromecambon to create the PR, you must first fork the vale-action repository, push your changes to this fork and then you will be able to create a PR targeting the vale-action repo from your fork

**Comment by jeromecambon** [comment]
The issue https://github.com/errata-ai/vale-action/issues/84 is not fixed for a while, so we can close this issue, since Vale has been disabled.

**Comment by jeromecambon** [comment]
Seeting the right close reason.
