### ISSUE TITLE
Apply the "Vale checks" to doc content repositories without duplication

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#499]
The Vale checks are currently only running in the `bonita-doc` repository. Notice we currently have some issue with Vale: #464

The checks need to be also added to other repositories but in the same way we do for other workflow/actions/checks: see  #422

**Comment by jeromecambon** [comment]
The issue https://github.com/errata-ai/vale-action/issues/84 is not fixed for a while, so we can close this issue, since Vale has been disabled.

**Comment by jeromecambon** [comment]
The issue https://github.com/errata-ai/vale-action/issues/84 is not fixed for a while, so we can close this issue, since Vale has been disabled.
