### ISSUE TITLE
Integrate the Bonita Javadoc static resources

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#55]
**Remark**: this is something similar to what we could need for #39.

The javadoc is currently available via url like http://documentation.bonitasoft.com/javadoc/api/7.11/index.html and is not part of the documentation content repository. It is pushed directly on the server.
**Note**: We also have groovy doc

### Possible solutions (to be discussed, non exhaustive list)

- do not publish the javadoc:
  - pros: already available in another ways, in particular in developer IDE
    - community: already available via https://javadoc.io/doc/org.bonitasoft.engine/bonita-client/latest/index.html and available on maven central as javadoc jar. Also available for dedicated version: https://javadoc.io/doc/org.bonitasoft.engine/bonita-client/7.11.4/index.html
    - enterprise: available from the Bonitasoft Customer Portal as javadoc jar
  - cons
    - no more all-in-one Community/Enterprise Javadoc as the one currently published in the documentation
- push the javadoc to a dedicated repository that will host a gh-pages branch. For instance, in the https://github.com/bonitasoft/bonita-platform-releases repository
  - pros
    - this repository is already managed by the Bonitasoft IT Team which is currently in charge of publishing the javadoc to the documentation site
    - this would keep the main documentation only generated by Antora: we can easily recreate from scratch, don't have to manage deletion or move manually
    - avoid growing the site size: already `359 MB` in 2a0a6fd
- push the javadoc directly at the same place as the rest of the documentation and manage links in the documentation
  - pros: easy to update, no extra antora configuration
  - cons: out of the rest of the generate site, we can not create a fresh environment, clean the existing gh-pages (so files deletion will have to be managed manually). This may have been possible when we were deploying to gh-pages as we can update the content of the branch, for netlify, this would require extra step to aggregate the generated content with the javadoc content and push everything at the same time and every time the doc content changes
- create a javadoc Antora component and store the static file in a dedicated branch of bonita-doc or in a new repository

#### Urls to the javadoc

At 1st glance, the javadoc url could change as they are not supposed to be indexed so we shouldn't be forced to keep the original urls.
When we will have redirect capabilities (#117), we will be able to put redirect from old redirect to new one (or if needed, setup rewrite rules)

#### Links to javadoc

**Note**: this is independent of the choosen hosting solution 

> how do we set links to javadoc in the source documentation content. Currently, the url is hard coded and the version is managed via a variable (see also #54). We could use a single Asciidoctor attribute that contains the full url.

**Comment by benjaminParisel** [comment]
We need to talk with IT team

**Comment by nchabanoles** [comment]
I think it is important the the Javadoc can be browsed online and not only in an IDE. That is the reason why Java itself let developper browse their API online. The same way many product do.

Now I agree, we need to find a solution that is easy to maintain and that do not require many manual actions to release.

Here are my thoughts on the requirements (I'll let you discuss the potential solutions):
* the javadoc should be accessible from the doc-site (either embedded or link to another hosting, for now I do not know if it matters to me)
* the javadoc should contain both Community and Enterprise APIs, to let developers have the full picture in one place

**Comment by jbaudot85** [comment]
I like above solutions 2 and 4 ("push the javadoc to a dedicated repository that will host a gh-pages branch" and "create a javadoc Antora component and store the static file in a dedicated branch of bonita-doc or in a new repository").

They seem equivalent solutions and inline with nicolas' requirements as soon as pointed out by the docsite.

**Comment by benjaminParisel** [comment]
- [ ] IT Team need to deployed the javadoc somewhere (github repository with github could be great)

- [ ] Replace the oldest link of javadoc with newest

**Comment by tbouffard** [comment]
solutions put in place, so closing
