### ISSUE TITLE
Tool: detect pages that don't include an AsciiDoc "description" attribute

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#591]
IMPORTANT: Be aware of #422

The attribute is needed to improve SEO and it is described as such in the contributing guide: https://github.com/bonitasoft/bonita-documentation-site/blob/b681fad6558299ae8027a749aa11121837a23d99/docs/content/CONTRIBUTING.adoc#contribution-check.
The check could be done as part of the repository content checks.
A lot of pages in the cloud repository don't declare the attribute.

**Comment by benjaminParisel** [comment]
First action has been created here: https://github.com/bonitasoft/actions/pull/115

In this PR, we added a "step" to validate if an attribute exist in updated file.

At same time, i added another step (to validate if multiple step work), it's the actual Forbidden Link action (actually it's the pr-diff-checker action). Now (with this new action) this check is done in the complete file updated, not only on the specific line updated.

**Comment by benjaminParisel** [comment]
We need to use this action in:

- [ ] bonita-doc
- [ ] bonita-cloud-doc
- [ ] bonita-continous delivery-doc
