### ISSUE TITLE
`undefined/undefined` listed in the "Check the pages that have been modified" PR comment

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-site#732]
I have recently seen this in https://github.com/bonitasoft/bonita-doc/pull/2715#issuecomment-2147819787
In this PR, the updated files are
- a regular page
- a navigation file

![image](https://github.com/bonitasoft/bonita-documentation-site/assets/27200110/1c083581-6686-4029-9611-4d0e36da3ca4)

It seems that the bug #534 is not fully fixed by #674.

**Note**: implementing  #766 may help

**Comment by benjaminParisel** [comment]
Closed with this PR -> https://github.com/bonitasoft/bonita-documentation-site/pull/787
