### ISSUE TITLE
Maybe wrong Bonita Platform Version indicated

### ISSUE THREAD

**Issue by ShamsGolap** [bonitasoft/bonita-documentation-site#798]
Hello,
I was reading this page : https://documentation.bonitasoft.com/bonita/2024.2/version-update/product-versioning#technical-id

It is about the version 2024.2, however as you can see in the following screen capture, there might be a mistake on the Bonita Platform Version : 
![image](https://github.com/user-attachments/assets/30ee6082-4e49-41d6-8103-de77c204e30e)

**Comment by tbouffard** [comment]
Thanks for your feedback @ShamsGolap, you are right, this is a typo that has not been fixed as part of https://github.com/bonitasoft/bonita-doc/pull/2849/files.
I have created https://github.com/bonitasoft/bonita-doc/pull/2910 to fix the problem.

**Comment by benjaminParisel** [comment]
PR merged, we can close this issue, thanks for your feedback.
