### ISSUE TITLE
Migrate documentation content

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#93]
* Migrate Bonita documentation for branch 7.3 to ~7.13~2021.2
* Migrate  Bici doc
* Migrate  Bonita cloud documentation
* Migrate last version of BCD and check if we can remove old last version (it's not working atm)

**Comment by tbouffard** [comment]
All documentation branches have been migrated and we now use the definitive branch name to build the site (see #199, #200 and #201). The converted content will be reviewed and specific fixes added on demand.
So closing
