### ISSUE TITLE
[doc content] fix links to previously generated pages that don't exist anymore

### ISSUE THREAD

**Issue by benjaminParisel** [bonitasoft/bonita-documentation-site#96]
* Before new doc site, we get some generic pages (started with _), to redirect user for a global category. These pages were generated.
* Now this pages aren't generated so we cannot reference links to such missing pages
* they existed in the taxonomy: this should have been fixed as part of the md-adoc conversion
* in other pages: they can be found by searching for `xref:_`

For example on BCD: for now, i have redirect _how-to.md link to aws_prerequisites.adoc

Check: 
- [x] Bonita
  - [x] 7.9: https://github.com/bonitasoft/bonita-doc/pull/1494 (merged into 7.9 and merged into other branches)
  - [ ] 7.10 
  - [ ] 7.11 
  - [ ] 2021.1
  - [ ] 2021.2
- [x] Cloud
- [x] BCD
- [x] BICI/Labs

**Comment by tbouffard** [comment]
xref validation pass, so everything is fixed.
